### ISSUE TITLE
UnboundLocalError: local variable 'labels' referenced before assignment and KeyError: 'machine-1-1'

### ISSUE THREAD

**Issue by huqiulan** [17000cyh/IMDiffusion#4]
run:      python compute_score.py --dataset_name SMD
issue1:  Traceback (most recent call last):
  File "compute_score.py", line 281, in <module>
    best_f, best_proper, best_infor, threshold_infor_dict = compute_one_subset_one_strategy(
  File "compute_score.py", line 215, in compute_one_subset_one_strategy
    residual_list, labels
UnboundLocalError: local variable 'labels' referenced before assignment

run:      python ensemble_proper.py --dataset_name SMD
issue2:  ensemble for SMD in 30-3-skip-strategy ...
length of pkl path list is 0
Traceback (most recent call last):
  File "ensemble_proper.py", line 461, in <module>
    compute_one_data(args.dataset_name)
  File "ensemble_proper.py", line 446, in compute_one_data
    compute_one_strategy(data_id,strategy_name,
  File "ensemble_proper.py", line 320, in compute_one_strategy
    last_step_threshold = threshold_dict[machine_number]
![IMD-issue2](https://github.com/17000cyh/IMDiffusion/assets/49156371/b3f5c340-de7c-4f7d-b5b9-abab96c9e2d8)
![IMD-issue1](https://github.com/17000cyh/IMDiffusion/assets/49156371/01a2e752-8e8f-4702-ba48-da85ed2b4360)

**Comment by WSake** [comment]
您好，请问您解决这个问题了吗？我也是在最后遇到了这个问题

**Comment by WSake** [comment]
您好，请问您解决这个问题了吗？我也是在最后遇到了这个问题。

**Comment by huqiulan** [comment]
我也还没解决，不知道怎么改，请问你有什么思路改代码吗？

**Comment by huqiulan** [comment]
我也没解决这个问题，发邮件问了作者，作者也没回复，请问你现在有什么思路改这个代码了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "17000cyh/IMDiffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月30日(星期天) 晚上6:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [17000cyh/IMDiffusion] UnboundLocalError: local variable 'labels' referenced before assignment and KeyError: 'machine-1-1' (Issue #4)





 
您好，请问您解决这个问题了吗？我也是在最后遇到了这个问题

**Comment by 17000cyh** [comment]
应该是需要先做：

python compute_score.py --dataset_name SMD

来进行异常分数的计算，再做ensemble的，否则可能会导致labels读取不成功。

**Comment by huqiulan** [comment]
I'm following the procedure of executing python compute_score.py --dataset_name SMD first, then python ensemble_proper.py --dataset_name SMD, and compute_score.py still has the same error.How do I solve this?
