### ISSUE TITLE
file exist error

### ISSUE THREAD

**Issue by shaieesss** [17000cyh/IMDiffusion#5]
作者您好，有个小问题，SMD数据集在训练时定义了data_set_number，代码如下：
data_set_number = ["3-4",'3-5',"3-10","3-11","1-5","1-8","2-4"]
data_set_number += ["1-1","1-2","1-3","1-4","1-5","1-6","1-7","1-8"]
data_set_number += ["2-1","2-2","2-3","2-4","2-5","2-6","2-7","2-8","2-9"]
data_set_number += ["3-1","3-2","3-3","3-4","3-5","3-6","3-7","3-8","3-9","3-10","3-11"]
请问，第一行代码中由1-5，而第二行代码又加入了一遍1-5，这样是否会导致后续mkdir（name, mode）时显示错误File exists。（因为我运行时出现了这个错误，说train_result/save0/...1-5..文件已经存在）

**Comment by 17000cyh** [comment]
哈喽您好，这里应该确实是有问题的。感谢指出，我后续修改，谢谢。

2024-08-05 20:51:45 "sdaioje" ***@***.***> 写道：

作者您好，有个小问题，SMD数据集在训练时定义了data_set_number，代码如下：
data_set_number = ["3-4",'3-5',"3-10","3-11","1-5","1-8","2-4"]
data_set_number += ["1-1","1-2","1-3","1-4","1-5","1-6","1-7","1-8"]
data_set_number += ["2-1","2-2","2-3","2-4","2-5","2-6","2-7","2-8","2-9"]
data_set_number += ["3-1","3-2","3-3","3-4","3-5","3-6","3-7","3-8","3-9","3-10","3-11"]
请问，第一行代码中由1-5，而第二行代码又加入了一遍1-5，这样是否会导致后续mkdir（name, mode）时显示错误File exists。（因为我运行时出现了这个错误，说train_result/save0/...1-5..文件已经存在）

**Comment by huqiulan** [comment]
Do you have these problems when you run it and how do you solve them, kindly help me!
run: python compute_score.py --dataset_name SMD
issue1: Traceback (most recent call last):
File "compute_score.py", line 281, in
best_f, best_proper, best_infor, threshold_infor_dict = compute_one_subset_one_strategy(
File "compute_score.py", line 215, in compute_one_subset_one_strategy
residual_list, labels
UnboundLocalError: local variable 'labels' referenced before assignment

run: python ensemble_proper.py --dataset_name SMD
issue2: ensemble for SMD in 30-3-skip-strategy ...
length of pkl path list is 0
Traceback (most recent call last):
File "ensemble_proper.py", line 461, in
compute_one_data(args.dataset_name)
File "ensemble_proper.py", line 446, in compute_one_data
compute_one_strategy(data_id,strategy_name,
File "ensemble_proper.py", line 320, in compute_one_strategy
last_step_threshold = threshold_dict[machine_number]

**Comment by shaieesss** [comment]
> Do you have these problems when you run it and how do you solve them, kindly help me! run: python compute_score.py --dataset_name SMD issue1: Traceback (most recent call last): File "compute_score.py", line 281, in best_f, best_proper, best_infor, threshold_infor_dict = compute_one_subset_one_strategy( File "compute_score.py", line 215, in compute_one_subset_one_strategy residual_list, labels UnboundLocalError: local variable 'labels' referenced before assignment
> 
> run: python ensemble_proper.py --dataset_name SMD issue2: ensemble for SMD in 30-3-skip-strategy ... length of pkl path list is 0 Traceback (most recent call last): File "ensemble_proper.py", line 461, in compute_one_data(args.dataset_name) File "ensemble_proper.py", line 446, in compute_one_data compute_one_strategy(data_id,strategy_name, File "ensemble_proper.py", line 320, in compute_one_strategy last_step_threshold = threshold_dict[machine_number]

actually I find the code have many errors, I didn't even run compute_score because I was struggled in running exe_machine.py. So I give up this.

**Comment by huqiulan** [comment]
May I ask if you are researching diffusion models? Do you have any ideas now? If you are interested in diffusion models, I would like to discuss and exchange ideas with you. I feel it is too difficult and there are not many codes that can run smoothly. Looking forward to your reply.


---Original---
From: ***@***.***&gt;
Date: Thu, Sep 5, 2024 16:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5)




  
Do you have these problems when you run it and how do you solve them, kindly help me! run: python compute_score.py --dataset_name SMD issue1: Traceback (most recent call last): File "compute_score.py", line 281, in best_f, best_proper, best_infor, threshold_infor_dict = compute_one_subset_one_strategy( File "compute_score.py", line 215, in compute_one_subset_one_strategy residual_list, labels UnboundLocalError: local variable 'labels' referenced before assignment
 
run: python ensemble_proper.py --dataset_name SMD issue2: ensemble for SMD in 30-3-skip-strategy ... length of pkl path list is 0 Traceback (most recent call last): File "ensemble_proper.py", line 461, in compute_one_data(args.dataset_name) File "ensemble_proper.py", line 446, in compute_one_data compute_one_strategy(data_id,strategy_name, File "ensemble_proper.py", line 320, in compute_one_strategy last_step_threshold = threshold_dict[machine_number]
  
actually I find the code have many errors, I didn't even run compute_score because I was struggled in running exe_machine.py. So I give up this.

**Comment by shaieesss** [comment]
in the past few weeks i want to study diffusion model and i also find it is not many available code so i change the direction but i welcome any communication and collaberation. you can send me your wechat through ***@***.***

| |
msezwx
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 09/05/2024 16:30 |
| To | 17000cyh/IMDiffusion ***@***.***> |
| Cc | sdaioje ***@***.***>,
Author ***@***.***> |
| Subject | Re: [17000cyh/IMDiffusion] file exist error (Issue #5) |

May I ask if you are researching diffusion models? Do you have any ideas now? If you are interested in diffusion models, I would like to discuss and exchange ideas with you. I feel it is too difficult and there are not many codes that can run smoothly. Looking forward to your reply.


---Original---
From: ***@***.***&gt;
Date: Thu, Sep 5, 2024 16:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5)





Do you have these problems when you run it and how do you solve them, kindly help me! run: python compute_score.py --dataset_name SMD issue1: Traceback (most recent call last): File "compute_score.py", line 281, in best_f, best_proper, best_infor, threshold_infor_dict = compute_one_subset_one_strategy( File "compute_score.py", line 215, in compute_one_subset_one_strategy residual_list, labels UnboundLocalError: local variable 'labels' referenced before assignment

run: python ensemble_proper.py --dataset_name SMD issue2: ensemble for SMD in 30-3-skip-strategy ... length of pkl path list is 0 Traceback (most recent call last): File "ensemble_proper.py", line 461, in compute_one_data(args.dataset_name) File "ensemble_proper.py", line 446, in compute_one_data compute_one_strategy(data_id,strategy_name, File "ensemble_proper.py", line 320, in compute_one_strategy last_step_threshold = threshold_dict[machine_number]

actually I find the code have many errors, I didn't even run compute_score because I was struggled in running exe_machine.py. So I give up this.

**Comment by huqiulan** [comment]
This is wechat ：Augenstern_B-612



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 5, 2024 16:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5)




 in the past few weeks i want to study diffusion model and i also find it is not many available code so i change the direction but i welcome any communication and collaberation. you can send me your wechat through ***@***.***
 
 | |
 msezwx
 |
 |
 ***@***.***
 |
 ---- Replied Message ----
 | From | ***@***.***&gt; |
 | Date | 09/05/2024 16:30 |
 | To | 17000cyh/IMDiffusion ***@***.***&gt; |
 | Cc | sdaioje ***@***.***&gt;,
 Author ***@***.***&gt; |
 | Subject | Re: [17000cyh/IMDiffusion] file exist error (Issue #5) |
 
 May I ask if you are researching diffusion models? Do you have any ideas now? If you are interested in diffusion models, I would like to discuss and exchange ideas with you. I feel it is too difficult and there are not many codes that can run smoothly. Looking forward to your reply.
 
 
 ---Original---
 From: ***@***.***&amp;gt;
 Date: Thu, Sep 5, 2024 16:23 PM
 To: ***@***.***&amp;gt;;
 Cc: ***@***.******@***.***&amp;gt;;
 Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5)
 
 
 
 
 
 Do you have these problems when you run it and how do you solve them, kindly help me! run: python compute_score.py --dataset_name SMD issue1: Traceback (most recent call last): File "compute_score.py", line 281, in best_f, best_proper, best_infor, threshold_infor_dict = compute_one_subset_one_strategy( File "compute_score.py", line 215, in compute_one_subset_one_strategy residual_list, labels UnboundLocalError: local variable 'labels' referenced before assignment
 
 run: python ensemble_proper.py --dataset_name SMD issue2: ensemble for SMD in 30-3-skip-strategy ... length of pkl path list is 0 Traceback (most recent call last): File "ensemble_proper.py", line 461, in compute_one_data(args.dataset_name) File "ensemble_proper.py", line 446, in compute_one_data compute_one_strategy(data_id,strategy_name, File "ensemble_proper.py", line 320, in compute_one_strategy last_step_threshold = threshold_dict[machine_number]
 
 actually I find the code have many errors, I didn't even run compute_score because I was struggled in running exe_machine.py. So I give up this.

**Comment by starry-ZRY** [comment]
I am also researching diffusion models and would like to connect with you both to exchange ideas. Can we connect on WeChat?

**Comment by shaieesss** [comment]
shebro1

| |
msezwx
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 09/18/2024 10:36 |
| To | 17000cyh/IMDiffusion ***@***.***> |
| Cc | sdaioje ***@***.***>,
Author ***@***.***> |
| Subject | Re: [17000cyh/IMDiffusion] file exist error (Issue #5) |

I am also researching diffusion models and would like to connect with you both to exchange ideas. Can we connect on WeChat?

**Comment by huqiulan** [comment]
Sure, you can tell me your WeChat and I'll add you.




---Original---
From: ***@***.***&gt;
Date: Wed, Sep 18, 2024 10:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5)




 
I am also researching diffusion models and would like to connect with you both to exchange ideas. Can we connect on WeChat?

**Comment by shaieesss** [comment]
> I am also researching diffusion models and would like to connect with you both to exchange ideas. Can we connect on WeChat?

shebro1

**Comment by starry-ZRY** [comment]
zrry1129

> Sure, you can tell me your WeChat and I'll add you.
> 当然，你可以告诉我你的微信，我会添加你。
> […](#) [...](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Sep 18, 2024 10:36 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5) I am also researching diffusion models and would like to connect with you both to exchange ideas. Can we connect on WeChat? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by 1202huan** [comment]
> 请问你有没有在研究扩散模型？你现在有什么想法吗？如果你对扩散模型感兴趣，我想和你讨论和交流。我觉得太难了，能顺利运行的代码也不多。期待你的回复。
> […](#)

兄弟，我也刚刚接触这个，能和您交流一下嘛

**Comment by 1202huan** [comment]
> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？

兄弟，我也刚刚接触这个，能和您交流一下嘛

**Comment by huqiulan** [comment]
v：Augenstern_B-612



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 21, 2025 11:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5)


    
我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？
  
兄弟，我也刚刚接触这个，能和您交流一下嘛

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  1202huan left a comment (17000cyh/IMDiffusion#5)
  
我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？
  
兄弟，我也刚刚接触这个，能和您交流一下嘛

**Comment by shaieesss** [comment]
我其实最近没有整这个，因为这个方向做的确实一塌糊涂，我一般是图学习，时序异常检测，现在在接触vae生成，微信shebro1

| |
msezwx
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 03/21/2025 11:32 |
| To | 17000cyh/IMDiffusion ***@***.***> |
| Cc | sdaioje ***@***.***>,
Author ***@***.***> |
| Subject | Re: [17000cyh/IMDiffusion] file exist error (Issue #5) |
v：Augenstern_B-612 <br> <br> <br> <br> ---Original--- <br> From: ***@***.***&amp;gt; <br> Date: Fri, Mar 21, 2025 11:28 AM <br> To: ***@***.***&amp;gt;; <br> Cc: ***@***.******@***.***&amp;gt;; <br> Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5) <br> <br> <br> <br> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？ <br> <br> 兄弟，我也刚刚接触这个，能和您交流一下嘛 <br> <br> — <br> Reply to this email directly, view it on GitHub, or unsubscribe. <br> You are receiving this because you commented.Message ID: ***@***.***&amp;gt; <br> 1202huan left a comment (17000cyh/IMDiffusion#5) <br> <br> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？ <br> <br> 兄弟，我也刚刚接触这个，能和您交流一下嘛 <br> <br> — <br> Reply to this email directly, view it on GitHub, or unsubscribe. <br> You are receiving this because you commented.Message ID: ***@***.***&amp;gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

huqiulan left a comment (17000cyh/IMDiffusion#5)
v：Augenstern_B-612 <br> <br> <br> <br> ---Original--- <br> From: ***@***.***&amp;gt; <br> Date: Fri, Mar 21, 2025 11:28 AM <br> To: ***@***.***&amp;gt;; <br> Cc: ***@***.******@***.***&amp;gt;; <br> Subject: Re: [17000cyh/IMDiffusion] file exist error (Issue #5) <br> <br> <br> <br> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？ <br> <br> 兄弟，我也刚刚接触这个，能和您交流一下嘛 <br> <br> — <br> Reply to this email directly, view it on GitHub, or unsubscribe. <br> You are receiving this because you commented.Message ID: ***@***.***&amp;gt; <br> 1202huan left a comment (17000cyh/IMDiffusion#5) <br> <br> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？ <br> <br> 兄弟，我也刚刚接触这个，能和您交流一下嘛 <br> <br> — <br> Reply to this email directly, view it on GitHub, or unsubscribe. <br> You are receiving this because you commented.Message ID: ***@***.***&amp;gt;

**Comment by 1202huan** [comment]
> 我其实最近没有整这个，因为这个方向做的确实一塌糊涂，我一般是图学习，时序异常检测，现在在接触vae生成，微信shebro1微信| |msezwx 的|| ***@***.*** |---- 已回复 留言 ----|发件人 | ***@***.***> | |日期 |03/21/2025 11：32 ||至 |17000cyh/IMDiffusion ***@***.***> ||抄送 |sdaioje ***@***.***>，作者 ***@***.***> ||主题 |回复：[17000cyh/IMDiffusion] 文件存在错误（问题 [#5](https://github.com/17000cyh/IMDiffusion/issues/5)） |v：Augenstern_B-612 <br> <br> <br> <br> ---原文--- <br> 发件人：***@***.***& 燃气轮机; <br> 日期：2025 年 3 月 21 日星期五上午 11：28 <br> 收件人：***@***.***& 燃气轮机;; <br> 抄送： ***@***.******@***.***& 燃气轮机;;<br> 主题：回复：[17000cyh/IMDiffusion] 文件存在错误（问题 [#5](https://github.com/17000cyh/IMDiffusion/issues/5)） <br> <br> <br> <br> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？<br> <br> 兄弟，我也刚刚接触这个，能和您交流一下嘛 <br> <br> — <br> 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。<br> 您收到此邮件是因为您发表了评论。消息 ID：***@***.***& 燃气轮机;<br> 1202huan 留言 （[17000cyh/IMDiffusion#5](https://github.com/17000cyh/IMDiffusion/issues/5)） <br> <br> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？<br> <br> 兄弟，我也刚刚接触这个，能和您交流一下嘛 <br> <br> — <br> 直接回复此邮件，在 GitHub 上查看，或取消订阅。<br> 您收到此邮件是因为您发表了评论。消息 ID：***@***.***& 燃气轮机; —-直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此电子邮件是因为您编写了该线程。消息 ID：***@***.***>虎秋蓝留言 （[17000cyh/IMDiffusion#5](https://github.com/17000cyh/IMDiffusion/issues/5)）v：Augenstern_B-612 <br> <br> <br> <br> ---原文--- <br> 发件人： ***@***.***& 燃气轮机; <br> 日期：2025 年 3 月 21 日星期五上午 11：28 <br> 收件人：***@***.***& 燃气轮机;; <br> 抄送： ***@***.******@***.***& 燃气轮机;;<br> 主题：回复：[17000cyh/IMDiffusion] 文件存在错误（问题 [#5](https://github.com/17000cyh/IMDiffusion/issues/5)） <br> <br> <br> <br> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？<br> <br> 兄弟，我也刚刚接触这个，能和您交流一下嘛 <br> <br> — <br> 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。<br> 您收到此邮件是因为您发表了评论。消息 ID：***@***.***& 燃气轮机;<br> 1202huan 留言 （[17000cyh/IMDiffusion#5](https://github.com/17000cyh/IMDiffusion/issues/5)） <br> <br> 我也在研究扩散模型，并希望与你们俩联系以交流想法。我们可以在 WeChat 上联系吗？<br> <br> 兄弟，我也刚刚接触这个，能和您交流一下嘛 <br> <br> — <br> 直接回复此邮件，在 GitHub 上查看，或取消订阅。<br> 您收到此邮件是因为您发表了评论。消息 ID：***@***.***& 燃气轮机; —直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此电子邮件是因为您编写了该线程。消息 ID：***@***.***>
你好，昵称是啤酒饮料矿泉水吗哈哈哈
